# Generated by Django 4.2.16 on 2024-11-11 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Voter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_name", models.TextField()),
                ("first_name", models.TextField()),
                ("street_num", models.IntegerField()),
                ("street_name", models.TextField()),
                ("apt_num", models.TextField(blank=True)),
                ("zip", models.CharField(max_length=5)),
                ("dob", models.CharField(max_length=10)),
                ("dor", models.CharField(max_length=10)),
                ("party", models.CharField(max_length=1)),
                ("p_num", models.CharField(max_length=2)),
                ("v20state", models.BooleanField()),
                ("v21town", models.BooleanField()),
                ("v21primary", models.BooleanField()),
                ("v22general", models.BooleanField()),
                ("v23town", models.BooleanField()),
                ("v_score", models.IntegerField()),
            ],
        ),
    ]
