# Generated by Django 4.2.16 on 2024-11-11 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voter_analytics", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voter",
            name="dob",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="voter",
            name="dor",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="voter",
            name="p_num",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="voter",
            name="party",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="voter",
            name="v20state",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="voter",
            name="v21primary",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="voter",
            name="v21town",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="voter",
            name="v22general",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="voter",
            name="v23town",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="voter",
            name="v_score",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="voter",
            name="zip",
            field=models.TextField(),
        ),
    ]
