# Generated by Django 4.2.16 on 2024-11-12 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "voter_analytics",
            "0002_alter_voter_dob_alter_voter_dor_alter_voter_p_num_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="voter",
            name="party",
            field=models.CharField(max_length=2),
        ),
    ]
