# Generated by Django 4.2.16 on 2024-11-30 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rpg", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="coins",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
