# Generated by Django 4.2.16 on 2024-11-30 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rpg", "0002_character_coins"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="exp",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
