# Generated by Django 4.2.16 on 2024-12-10 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rpg", "0003_character_exp"),
    ]

    operations = [
        migrations.CreateModel(
            name="Enemy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("img", models.ImageField(upload_to="")),
                ("difficulty", models.TextField()),
                ("hp", models.IntegerField()),
                ("attack", models.IntegerField()),
                ("coin_reward", models.IntegerField()),
                ("exp_reward", models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name="character",
            name="mp",
        ),
        migrations.AddField(
            model_name="character",
            name="attack",
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="item",
            name="attack",
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="item",
            name="hp",
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="item",
            name="uses",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
