# Generated by Django 4.2.16 on 2024-12-10 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rpg", "0004_enemy_remove_character_mp_character_attack_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="enemy",
            name="total_hp",
            field=models.IntegerField(default=7),
            preserve_default=False,
        ),
    ]
