# Generated by Django 4.2.16 on 2024-12-10 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rpg", "0007_character_enemies_defeated"),
    ]

    operations = [
        migrations.AddField(
            model_name="achievement",
            name="timestamp",
            field=models.DateTimeField(default="2024-12-9 14:30:59"),
            preserve_default=False,
        ),
    ]
